# Generated by Django 4.2.16 on 2024-11-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='rate',
        ),
    ]
