# Generated by Django 4.2.16 on 2024-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0002_remove_position_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='wolny', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
