# Generated by Django 4.2.16 on 2024-11-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0004_employee_is_main_alter_employee_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_main',
        ),
    ]
