# Generated by Django 4.2.16 on 2024-11-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0007_remove_employee_projects_alter_employee_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emplotees',
            field=models.ManyToManyField(blank=True, to='shipyard_management.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
