# Generated by Django 4.2.16 on 2024-11-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0008_project_emplotees_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='emplotees',
            new_name='employees',
        ),
    ]
