# Generated by Django 4.2.16 on 2024-11-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0010_rename_projects_employee_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='project',
            new_name='projects',
        ),
    ]
