# Generated by Django 4.2.16 on 2024-11-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0011_rename_project_employee_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contactperson',
            old_name='first_name',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='contactperson',
            old_name='last_name',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='contactperson',
            old_name='phone_number',
            new_name='contact_phone_number',
        ),
    ]
