# Generated by Django 4.2.16 on 2024-11-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0013_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='shipyard_management.employee'),
        ),
    ]
