# Generated by Django 4.2.16 on 2025-01-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0014_alter_certificate_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('shift', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipyard_management.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipyard_management.project')),
            ],
            options={
                'unique_together': {('employee', 'week_start_date')},
            },
        ),
    ]
