# Generated by Django 4.2.16 on 2025-01-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0015_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
