# Generated by Django 4.2.16 on 2025-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0016_remove_project_end_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rotation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rotation',
            name='weeks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rotation',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rotation',
            unique_together={('employee', 'project', 'year')},
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='week_start_date',
        ),
    ]
