# Generated by Django 4.2.16 on 2025-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipyard_management', '0017_alter_rotation_unique_together_rotation_weeks_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rotation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rotation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotation',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='weeks',
        ),
    ]
